# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2022 Roland Csaszar
#
# Project:  notoy-pwa
# File:     build.yml
# Date:     13.Feb.2022
#
# ==============================================================================


name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --dev
    - run: npm install --save-dev purescript
    - run: npm run build >> build.txt 2>&1

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      if: ${{ always() }}
      with:
        name: "Build report"
        if-no-files-found: ignore
        path: build.txt

  bundle:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --dev
    - run: npm install --save-dev purescript
    - run: npm run bundle >> bundle.txt 2>&1

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      if: ${{ always() }}
      with:
        name: "Build report"
        if-no-files-found: ignore
        path: bundle.txt
